[parity]
chain = "/shared/config/chain0.json"
base_path = "/data/parity"

[network]
min_peers = 0

[mining]
gas_floor_target = "60000000"
tx_gas_limit = "60000000"
gas_cap = "60000000"

[rpc]
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "parity_accounts", "parity_set"]
