[parity]
chain = "/shared/config/chain0.json"
base_path = "/data/parity"

[network]
min_peers = 1

[rpc]
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "parity_accounts"]
