variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "project_id" {}
variable "fw_node_filter" {}
variable "k8s_config_path" {}
variable "k8s_host" {}
variable "data_volume" {}
variable "parity_config" {}
variable "parity_secret" {}
variable "setup_path" {}
